theme: jekyll-theme-minimal
logo: "/hooreen.png"

title: Hooreen Ansari
description: Mechanical Engineer

# Social Media Links
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/hooreenansari/"
    icon: "fab fa-linkedin"
  - name: "Gmail"
    url: "mailto:hooreenansari04@gmail.com"
    icon: "fas fa-envelope"

# Additional Customization (if needed)
minima:
  skin: "dark"
  social_links:
    linkedin: "https://www.linkedin.com/in/hooreenansari/"
    gmail: "mailto:hooreenansari04@gmail.com"
